export const STATUS = {
  NOT_WORKED: 'NOT_WORKED',
  APPROPVED: 'APPROPVED',
  REJECTED: 'REJECTED',
  SUMBMITED: 'SUMBMITED',
  WORKED: 'WORKED'
};

export type STATUS_TYPE = (typeof STATUS)[keyof typeof STATUS]